spring:
  profiles:
    active: production
cloud:
  aws:
    stack:
      # CloudFormationのstack名を自動収集しない
      auto: false
    region:
      # EC2のmetadataを自動収集しない
      auto: false
      static: ap-northeast-1
server:
  port: 80
  servlet:
    context-path: /backend-for-frontend
service:
  dns: internal-ccr-test-alb-private-1779157467.ap-northeast-1.elb.amazonaws.com